### ISSUE TITLE
Schema with dependencies not complete

### ISSUE THREAD

**Issue by datenmanagement-sdbb** [datenmanagement-sdbb/eCH-0260#10]
See feedback ct. NE:

eCH-0011-f/9 manque l’import de eCH-0006/3 et eCH-0135/2
eCH-0108/7 manque l’import de eCH-0129/6
eCH-0021-f/8 manque l’import de  eCH-0006/3

To be added in eCH-0260-PDF

**Comment by lars-steffen** [comment]
Verstehe ich es richtig, dass es hier nur um die Darstellung in Abbildung 2 geht? Dort habe ich absichtlich nur diejenigen aufgeführt, welche direkt in eCH-0260 vorkommen. Eine Anpassung ist kein Problem, macht aber die Grafik etwas unübersichtlicher.

**Comment by datenmanagement-sdbb** [comment]
Guten Tag

Besten Dank für Ihre Nachricht! Ihre Ticket-Nummer: MBD-JXFHZ-262

Sie werden spätestens in 3 Arbeitstagen eine Antwort erhalten. Anfragen, die vom SDBB als dringend erachtet werden, werden prioritär behandelt.

Freundliche Grüsse

SDBB | CSFO – [www.sdbb.ch](https://www.sdbb.ch)  
Schweizerisches Dienstleistungszentrum Berufsbildung | Berufs-, Studien- und Laufbahnberatung

---

Bonjour,

Nous avons bien reçu votre demande. Votre numéro de ticket: MBD-JXFHZ-262

Vous recevrez au plus tard une réponse dans les 3 jours ouvrables. Les demandes classées urgentes par le CSFO sont traitées en priorité.

Meilleures salutations,

SDBB | CSFO – [www.csfo.ch](https://www.csfo.ch)  
Centre suisse de services Formation professionnelle | orientation professionnelle, universitaire et de carrière

---

Buongiorno,

Abbiamo ricevuto la sua richiesta. Il suo numero di ticket: MBD-JXFHZ-262

Riceverà una risposta entro 3 giorni lavorativi. Le richieste classificate dal CSFO come urgenti avranno la priorità.

Cordiali saluti,

SDBB | CSFO – [www.csfo.ch](https://www.csfo.ch)  
Centro svizzero di servizio Formazione professionale | orientamento professionale, universitario e di carriera
