### ISSUE TITLE
Instructions for the use of complete data transmissions

### ISSUE THREAD

**Issue by datenmanagement-sdbb** [datenmanagement-sdbb/eCH-0260#13]
tbd

**Comment by wehrlilu** [comment]
Aktuell ist im Datenaustauschkonzept Kapitel 3.11 (Gesamtbestandsmeldungen) definiert: "Im Datenaustausch Berufsbildung werden in den täglichen Meldungen nur neue oder geänderte Datensätze übermittelt. In allen Meldungen können eines oder mehrere Elemente vorkommen. Bei Bedarf können zwischen zwei Teilnehmern so auch Gesamtbestandsmeldungen (welche alle für beide Stellen relevanten Datensätze beinhalten) übermittelt werden. Für diese Meldungen können die in Kapitel 4 beschriebenen Meldungsformate verwendet werden. Wenn die Gesamtbestandsmeldungen über sedex ausgetauscht werden, müssen diese mit einem im Vergleich zu den täglichen Meldungen unterschiedlichen Submeldungstypen (siehe Kapitel 5.6) gekennzeichnet werden. Für den Versand von Gesamtbestandsmeldungen gibt es keine weiteren Vorgaben in diesem Konzept. Der Versand soll bilateral zwischen den Teilnehmern vereinbart werden."
Frage: Braucht es weitere Vorgaben im Konzept?

**Comment by wehrlilu** [comment]
Entscheid AG-DA: Das wird so belassen. Wenn es Inkonsistenzen gibt, kann man diese anhand einer Gesamtbestandsmeldung bereinigen. Eine periodische Meldung soll nicht vorgeschrieben werden.
