### ISSUE TITLE
centrallyManaged only to be used in datatypes for LSR

### ISSUE THREAD

**Issue by datenmanagement-sdbb** [datenmanagement-sdbb/eCH-0260#15]
Also 2115 for example has the flag centrallyManaged as part of the hostCompanyType, but for other use cases than LSR, this is no applicable.

Workaround for now: Always send value 0 in other message types than 2108

**Comment by datenmanagement-sdbb** [comment]
Preferred solution: remove centrallyManaged from hostCompanyType and using it directly in VETAccreditationType

**Comment by wehrlilu** [comment]
-> kann intern geklärt werden (SDBB)

**Comment by wehrlilu** [comment]
Entscheid: centrallyManaged von hostCompanyType in den VETaccreditationType verschieben.
