### ISSUE TITLE
Birthdate for VETtrainers mandatory

### ISSUE THREAD

**Issue by datenmanagement-sdbb** [datenmanagement-sdbb/eCH-0260#16]
The birthdate for VETtrainers is mandatory (eCH-0044 personIdentificationType) but not used in Dat-Rili 3.07a. Is it known?

**Comment by wehrlilu** [comment]
AG-DA: Damit der eCH-Standard verwendet werden kann, wird das so belassen, auch wenn der Geburtstag inhaltlich nicht nötig ist.
