### ISSUE TITLE
phone number missing for representatives

### ISSUE THREAD

**Issue by datenmanagement-sdbb** [datenmanagement-sdbb/eCH-0260#17]
Phone number is missing for the type //element(*,eCH-0260:extendedEducationRelationType)/eCH-0260:educationRelation/eCH-0260:apprentice/eCH-0260:representative

**Comment by wehrlilu** [comment]
Entscheid AG-DA: Ergänzung wird so gemacht, können mehrere Nummern gemeldet werden für gesetzliche Vertreter.
