### ISSUE TITLE
correspondance language missing for VETtrainer

### ISSUE THREAD

**Issue by datenmanagement-sdbb** [datenmanagement-sdbb/eCH-0260#18]
see title

**Comment by datenmanagement-sdbb** [comment]
correspondance language is in hostCompany mandatory, but should as an optional field also be available for VETtrainers (as in Dat-Rili 3.07a, 1020)

**Comment by datenmanagement-sdbb** [comment]
Zu diskutieren in AG-DA: Ist Korrespondenzsprache für Lernende notwendig?

**Comment by wehrlilu** [comment]
Entscheid AG-DA: Wir nennen die Korrespondenzsprache auch auf für die Lernenden (obligatorisches Feld).
