### ISSUE TITLE
Inconsistency with extendeEducationRelationType

### ISSUE THREAD

**Issue by datenmanagement-sdbb** [datenmanagement-sdbb/eCH-0260#22]
It is expected in the process that as soon as a new apprenticeship contract is entered in the cantonal system, it is sent to DBLAP2/VODEX with the extendedEducationRelationType. However, the schoolYearDetails are also mandatory in this type, even though no information is available at this time.

Possible solutions:
- schoolYearDetails at XSD level optional, describe later delivery in the process
- Use of the EducationRelationType for the initial delivery (not extended), schoolYearDetails come separately later
- Further variants tbd

**Comment by wehrlilu** [comment]
In Konzept (und im PDF) beschreiben: wenn die Schulhalbtage nicht bekannt sind, wird in allen Feldern 0 gesendet.

**Comment by datenmanagement-sdbb** [comment]
Update in Version 2.1: extendedEducationRelationType wird nicht mehr benötigt, da im Zuge der Integration der zentralen Datenbank in den Prozess Schulorganiation die Types (educationRelationType und schoolDetailsType) sowieso auseinandergenommen wurden und nun zu getrennten Zeitpunkten und innerhalb unterschiedlicher Prozesse übermittelt werden
