### ISSUE TITLE
Best practice schoolIdType

### ISSUE THREAD

**Issue by martin-sorg-igib** [datenmanagement-sdbb/eCH-0260#23]
Im Zusammenhang mit dem Register Berufsfachschulen ist die Frage aufgetaucht, welche BSX-Codes im Datenaustausch gemäss eCH-0260 zu verwenden ist, bzw. ein gemeinsames Verständnis in der AG-DA zu erlangen wäre wünschenswert. Allenfalls könnte eine Best-Practice-Richtline erstellt oder der Standard präzisiert werden.

**Comment by datenmanagement-sdbb** [comment]
Es soll die neuen Nummer verwendet werden => zu ergänzen in Datenaustauschkonzept

**Comment by wehrlilu** [comment]
Im Datenaustauschkonzept schreiben wir bisher: "Für die Referenzierung in der beruflichen Grundbildung werden verschiedene Identifikatoren ver-wendet, die ermöglichen, Daten aus unterschiedlichen Datenquellen oder -lieferungen mit einer einheitlichen und trotzdem weitgehend offenen Codierung zu referenzieren. Die in der Berufsbil-dung verwendeten Identifikatoren sind im Datenstandard Berufsbildung (eCH-0260) beschrieben."
Vorschlag für Ergänzung: "Hinweis: Für die Referenzierung der Berufsfachschulen (schoolIdType, siehe eCH-0260 Kapitel 4.37) werden die neuen Lokations- resp. BSX-Codes verwendet. Diese enthalten am Schluss für die Institutionen ein .i und für Standorte ein .s.[Laufnummer]." und als Fussnote "Siehe https://www.sdbb.ch/datenmanagement/dienstleistungen/rbs/daten". 
Zu prüfen ist, ob die Ergänzung nicht im eCH-Standard (auch) erwähnt werden soll.

**Comment by lars-steffen** [comment]
Hinweis: Aktuell sind keine Punkte zugelassen, dies müsste angepasst werden. Aktuell zugelassen sind Ausdrücke, die folgendem regulärem Ausdruck entsprechen: BS[A-Z]{1}[A-Za-z0-9_-]{1,47}

**Comment by wehrlilu** [comment]
AG-DA: Vor Umsetzung eCH wird der heutige/bisherige Code verwendet. Mit Umstellung auf eCH werden die neuen Codes verwendet. 
Frage: Wo wird zugewiesen, Standort oder Institution? 
Vorschlag: Meldung Institution und Standort ermöglichen (zwei Elemente), Institution Pflichtfeld, Standort optional. 
Anpassung Standart und Konzept.

**Comment by datenmanagement-sdbb** [comment]
Gemäss https://github.com/datenmanagement-sdbb/eCH-0260/issues/23#issuecomment-2345649998 sollten wir 2 Felder haben für Institution und Standort, das ist aber nicht der Fall => to-do:

- schoolIdInstitution
- schoolIdPlace

Beide im Format der heutigen schoolId

**Comment by lars-steffen** [comment]
fixed in commit cba7203

**Comment by datenmanagement-sdbb** [comment]
Der Standort der Schule kann zwar nun übermittelt werden, das Feld ist jetzt aber als obligatorisch definiert. Gemäss https://github.com/datenmanagement-sdbb/eCH-0260/issues/23#issuecomment-2345649998 müsste dieses Feld optional geführt werden (nur Institution obligatorisch). @lars-steffen Bitte anpassen in Branch 2.2

**Comment by lars-steffen** [comment]
Umgestezt in 9e228e0
