### ISSUE TITLE
Missing mutation reason

### ISSUE THREAD

**Issue by datenmanagement-sdbb** [datenmanagement-sdbb/eCH-0260#24]
According to Ct. NE, annlutions of contracts before the beginning of the apprenticeship have to be treated differently. An additional mutation reason (T-types) has therefore to be added

**Comment by datenmanagement-sdbb** [comment]
- Mutation reason T05 "Annulation vor Lehrbeginn" has to be added
- All T-reasons have to be published in the eCH-0260 PDF (just as the M-reasons)

**Comment by lars-steffen** [comment]
Remark: Change is only necessary in eCH-0260 PDF, no change in XSD needed
