### ISSUE TITLE
T-mutation reasons cannot be transmitted

### ISSUE THREAD

**Issue by datenmanagement-sdbb** [datenmanagement-sdbb/eCH-0260#25]
Defined mutation reasons according to "SOLL-Prozesse" (chapter 5.3.2) cannot be transmitted in the terminationEducationRelationType

**Comment by lars-steffen** [comment]
In den SOLL-Prozessen wird unterschieden zwischen Mutationen mit Anpassung eines Bildungsverhältnisses (M01-M99) und Mutationen mit Auflösung eines Bildungsverhältnisses. D.h.: Soll dies technisch so unterschieden werden? D.h.: Aktuell erlaubt educationMutationReason nur die Werte M01 - M99. Soll dieser Typ um die Werte T01-T99 erweitert werden oder soll ein separater Typ erstellt werden?

**Comment by datenmanagement-sdbb** [comment]
Guten Tag

Besten Dank für Ihre Nachricht! Ihre Ticket-Nummer: DCZ-RMGHW-561

Sie werden spätestens in 3 Arbeitstagen eine Antwort erhalten. Anfragen, die vom SDBB als dringend erachtet werden, werden prioritär behandelt.

Freundliche Grüsse

SDBB | CSFO – [www.sdbb.ch](https://www.sdbb.ch)  
Schweizerisches Dienstleistungszentrum Berufsbildung | Berufs-, Studien- und Laufbahnberatung

---

Bonjour,

Nous avons bien reçu votre demande. Votre numéro de ticket: DCZ-RMGHW-561

Vous recevrez au plus tard une réponse dans les 3 jours ouvrables. Les demandes classées urgentes par le CSFO sont traitées en priorité.

Meilleures salutations,

SDBB | CSFO – [www.csfo.ch](https://www.csfo.ch)  
Centre suisse de services Formation professionnelle | orientation professionnelle, universitaire et de carrière

---

Buongiorno,

Abbiamo ricevuto la sua richiesta. Il suo numero di ticket: DCZ-RMGHW-561

Riceverà una risposta entro 3 giorni lavorativi. Le richieste classificate dal CSFO come urgenti avranno la priorità.

Cordiali saluti,

SDBB | CSFO – [www.csfo.ch](https://www.csfo.ch)  
Centro svizzero di servizio Formazione professionale | orientamento professionale, universitario e di carriera

**Comment by datenmanagement-sdbb** [comment]
Ich würde einen separaten Typ machen (bspw. educationTerminationReason, da er ja im terminationEducationRelationType verwendet werden soll). In diesem Typ sollen dann nur die T-Gründe zugelassen sein.
Mutation und Auflösung sind wirklich zwei unterschiedliche Dinge und müssen deshalb m.E. auseinandergehalten werden, was mit separaten Types besser (bzw. schon auf Ebene XSD) möglich ist.
