### ISSUE TITLE
VET-trainer mandatory, but not always available

### ISSUE THREAD

**Issue by datenmanagement-sdbb** [datenmanagement-sdbb/eCH-0260#26]
According to the canton of Neuchâtel, many apprenticeship contracts are only submitted to the canton in July. These are today delivered to the school immediately, as the start of school is imminent. However, it is often the case that the training company still has to submit documents (e.g. to the VET trainer) and the apprenticeship contract therefore cannot yet be approved.
However, according to the definition of the educationRelationType, the VET trainer must always be included.

Is this situation identical in the other cantons?

**Comment by wehrlilu** [comment]
Die AG-DA möchte keine Änderung am bestehenden Standard, sonst kann man nicht mehr anhand des Schemas prüfen, ob die Meldung mit Lehrvertrag auch einen Berufsbildner enthält. Rückmeldung: Wenn das in einem Kanton nicht geht, müsste eine individuelle Lösung gefunden werden.
