### ISSUE TITLE
Best practice - Datenaustausch

### ISSUE THREAD

**Issue by martin-sorg-igib** [datenmanagement-sdbb/eCH-0260#27]
Der Kanton LU hat eine Datenlieferung von ausserkantonal beschulten LE vom Kt. SZ erhalten, welche zwei LV mit der gleichen LV-Nummer enthielt. Die LV betrafen den gleichen LE, einmal den ursprünglichen LV und einmal die LV-Verlängerung (QV-Rep.).

Ich möchte den Fall zum Anlass nehmen, um darüber zu diskutieren, ob es sinnvoll wäre eine Best-Practice-Dokument für den Datenaustausch zu etablieren.

Ein weiterer Fall wäre "Verantwortliche Berufsbildner pro Bildungsbewilligung". Müssen die vBB pro BiBew eindeutig/einheitlich sein oder nicht? In KOMPASS ist dies so, da die vBB auf der BiBew erfasst werden. Falls dies in anderen Amtslösungen nicht der Fall ist, also vBB des gleichen Berufs und LB unterschiedlich sein können, müsste dies bei Verarbeitung im Datenaustausch kompassseitig berücksichtigt werden.

**Comment by datenmanagement-sdbb** [comment]
Guten Tag

Besten Dank für Ihre Nachricht! Ihre Ticket-Nummer: CQG-DZPXN-404

Sie werden spätestens in 3 Arbeitstagen eine Antwort erhalten. Anfragen, die vom SDBB als dringend erachtet werden, werden prioritär behandelt.

Freundliche Grüsse

SDBB | CSFO – [www.sdbb.ch](https://www.sdbb.ch)  
Schweizerisches Dienstleistungszentrum Berufsbildung | Berufs-, Studien- und Laufbahnberatung

---

Bonjour,

Nous avons bien reçu votre demande. Votre numéro de ticket: CQG-DZPXN-404

Vous recevrez au plus tard une réponse dans les 3 jours ouvrables. Les demandes classées urgentes par le CSFO sont traitées en priorité.

Meilleures salutations,

SDBB | CSFO – [www.csfo.ch](https://www.csfo.ch)  
Centre suisse de services Formation professionnelle | orientation professionnelle, universitaire et de carrière

---

Buongiorno,

Abbiamo ricevuto la sua richiesta. Il suo numero di ticket: CQG-DZPXN-404

Riceverà una risposta entro 3 giorni lavorativi. Le richieste classificate dal CSFO come urgenti avranno la priorità.

Cordiali saluti,

SDBB | CSFO – [www.csfo.ch](https://www.csfo.ch)  
Centro svizzero di servizio Formazione professionale | orientamento professionale, universitario e di carriera

**Comment by datenmanagement-sdbb** [comment]
- SOLL-Prozesse Kap. 5.3.1: Ist gemäss Beschreibung bei Repetition im gleichen Lehrbetrieb eine Mutation des bestehenden Bildungsverhältnisses (d.h. in Zukunft Mutationsmeldung mit bspw. Änderung Prüfungsjahr und Mutationsgrund M06). Benötigt es weitere Regelungen?
- In eCH kann es gemäss educationRelationType mehrere VETtrainer für die gleiche Bildungsbewilligung geben; in Dat-Rili gibt es eine Anweisung, das der Berufsbildner eindeutig sein muss. Wie soll das bei eCH sein? Zu regeln in Datenaustauschkonzept

Grundsätzlich wird von Best-Practice-Dokument abgeraten, es existieren Umsetzungsdokumente (bspw. Datenaustauschkonzept), die allenfalls ergänzt werden müssen mit unklaren Punkten.

**Comment by wehrlilu** [comment]
Zu der ersten Fragestellung: Entscheid für eCH: Repetitionen führen zu einem Wechsel des Teilverhältnisses innerhalb des gleichen Bildungsverhältnisses. Anpassung Datenaustauschkonzept Kapitel 3.9.2 und ev. Kap. 4.7. 
Zusätzlich: Anpassung M05 "mit oder ohne Schulbesuch" (HAKA und eCH)

**Comment by wehrlilu** [comment]
Zu der zweiten Frage: Redundanz zwischen VETtrainerRoleId und isMainResponsible? Ja
Entscheid: Wir lassen das Element isMainResponsible weg --> Anpassung eCH nötig. Bemerkung im PDF: Es kann genau einen verantwortlichen Berufsbildner geben pro Bildungsbewilligung. 
Es kann sein, dass der hauptverantwortliche Berufsbildner nicht gesendet wird, weil er in keinem Lehrvertrag hat. 
Es könnte eine eigene Transaktion für die Übermittlung der hauptverantwortlichen Berufsbildner definiert werden.
