### ISSUE TITLE
Processing sequence for message types

### ISSUE THREAD

**Issue by datenmanagement-sdbb** [datenmanagement-sdbb/eCH-0260#29]
Due to the abolition of the "Laufnummer", it was decided that a processing sequence for the message types should be defined (e.g. initial delivery before mutations, VETaccreditations before apprenticeship places, etc.). This point still needs to be completed and added to the data exchange concept.

**Comment by datenmanagement-sdbb** [comment]
Proposition NE:

![image](https://github.com/user-attachments/assets/343ff3e7-7df9-4a36-8b51-f6fb6e1b2a16)

**Comment by wehrlilu** [comment]
So far we defined the following principle in the data exchange concept (chapter 3.10): "Um die korrekte Verarbeitungsreihenfolge sicherzustellen, sollen Initialmeldungen (siehe Kapitel 2) vor Mutationsmeldungen (siehe Kapitel 4.7) verarbeitet werden." It probably makes sense to add "Bei Meldungen an LSR werden die Meldungen zu Lehrfirmen resp. Bildungsbewilligungen (VA1, VA2) vor den Meldungen zu Lehrstellen (AP2, AP3) verarbeitet". 

For which other message types do we really need strict rules? Is it necessary, to have an exact order?
