### ISSUE TITLE
Duplicated options for exam deregistration

### ISSUE THREAD

**Issue by marc-fuhrer-sdbb** [datenmanagement-sdbb/eCH-0260#3]
There are currently 2 ways to deregister from exams:

- examAssignmentType via examAssignmentKindType
- via mutation with the deregistrationFromOrganizationType

In the " Datenaustauschkonzept" it must be clarified which procedure should be chosen (or whether there are different use cases). Then eCH-0260 must be adjusted.

**Comment by datenmanagement-sdbb** [comment]
These can be used for 2 different use cases:

- complete deregistration from an exam (e.g. in case of apprenticeship termination)
- deregistration for just some elements (e.g. in case of an accident)

So neither element can be deleted, but it has to be clarified in the documents, in which case what element has to be used.

**Comment by datenmanagement-sdbb** [comment]
Resolved with version 3.0 Datenaustauschkonzept
