### ISSUE TITLE
PKX-code missing for examAssignmentType

### ISSUE THREAD

**Issue by datenmanagement-sdbb** [datenmanagement-sdbb/eCH-0260#32]
Wenn via examAssignmentType Daten an die zentrale Datenbank gesendet werden (Meldung EO1), muss die zentrale Datenbank wissen, an welche Prüfungsorganisation die Daten weitergeleitet werden müssen bzw. welche Organisation auf die Daten berechtigt werden muss. Heute fehlt aber diese Prüfungsorganisations-ID bzw. der Prüfungskanton (analog zu heutigen Dat-Rili Transaktion 2300).

Vorschlag: Prüfungorg.ID (PKX-Code) (optional) und Prüfungskanton (zwingend) als Felder im bestehenden Type ergänzen. Bei einer Verwendung des Types im Rahmen von EO2 oder EO3 wären diese Informationen nicht zwingend nötig, aber schaden auch nicht.

Alternative: Zwei Types definieren

1. Type für Lieferung Kanton => Prüfungsorganisation (PKX-Code zwingend)
2. Type für Lieferung Lehrortkanton => Prüfungskanton (Prüfungskanton zwingend, PKX-Code optional)

To be discussed in Arbeitsgruppe

**Comment by datenmanagement-sdbb** [comment]
Vorgeschlagene Lösung:

2 neue Felder
- Prüfungskanton (obligatorisch) => bei peer-to-peer-Austausch redundante Information, aber schadet nicht
- "Durchführende Prüfungsorganisation" (optional) => wird verwendet für Zuteilung Prüfungskanton zu Prüfungsorganisation

**Comment by lars-steffen** [comment]
PKX-codes haben wir als "Prüfungskommission" definiert. Ist das dasselbe wie "Prüfungsorganisation"? Wenn ja: Sollten wir nicht immer denselben Begriff verwenden? Wenn nein: Wie unterscheiden sich die beiden?

**Comment by lars-steffen** [comment]
Entscheid Abgleich Marc/Lukas/Lars --> Prüfungskommission
