### ISSUE TITLE
Schulorganisation für ZDB ergänzen

### ISSUE THREAD

**Issue by wehrlilu** [datenmanagement-sdbb/eCH-0260#34]
![image](https://github.com/user-attachments/assets/e457f0da-1292-4adf-96e6-9b86f618b38f)

Anpassung DAK, SOLL-Prozesse, eCH

**Comment by lars-steffen** [comment]
extendedEducationRelationType kommt nur in dbResponseCourseOrganisationType vor: Vorschlag: Typ löschen und in dbResponseCourseOrganisationType ersetzen durch educationRelationType und schoolYearDetailsType.
--> OK?

**Comment by lars-steffen** [comment]
dbResponseCourseOrganisationType allenfalls auch für Rückmeldungen an Schulen verwenden? Dann müsste er umbenannt werden.
